### ISSUE TITLE
deberia existir un boton para eliminar el sonido

### ISSUE THREAD

**Issue by llambias** [v4rgas/sortEm#3]

**Comment by v4rgas** [comment]
tienes razon, me habia dado lata implementarlo por como hice lo de los sonidos pero es wen momento para arreglarlo

**Comment by v4rgas** [comment]
52c08ee

**Comment by v4rgas** [comment]
No lo implemente en telefono pq no se que controles utilizar para eso, pero esta listo para browser

52c08ee
